site_name: is-a.dev documentation

theme:
  name: material
  favicon: img/favicon.ico
  logo: img/banner.png
  palette: 
    - scheme: default
      toggle:
        icon: material/toggle-switch 
        name: Switch to dark mode
    - scheme: slate 
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to light mode

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
  - Home: index.md
  - GitHub Pages: github_pages/index.md
  - Hashnode Blog: hashnode/index.md
  - Other Guides: guides/index.md
